<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>JS错误处理</title>
</head>

<body>
    <script>
        /**
         * 1. 语法固定 try...catch
         * 2. catch 里的形参可以改变
         */
        /**
         * 1. try catch捕获到错误之后, 后续代码可以继续执行
         * 2. catch 可以将错误信息捕获到. e 是一个对象, 有message和stack两个属性
         * 3. 抛出错误之后, 在后续的 try 里面的代码不会执行
         * 4. try 不能捕获语法错误
         * 5. 允许使用 throw 手动的抛出错误
         * 6. 抛出任意类型的数据
         */
        // console.log(111);
        try {
            // console.log(222);
            // const foo = {};
            // foo();
            //除法运算
            // let a = 100;
            // let b = 0;
            // if(b === 0) throw new Error('除数不能为 0 ');
            // let res = a/b;
            // console.log(res);
            // console.log('不会输出');
            throw 'abc';
        } catch (e) {
            console.log(e);
            // console.log(e.message);
            // console.log(e.stack);// stack 栈
        }

        console.log(333);


        
    </script>
</body>

</html>